### ISSUE TITLE
Proposal #12 - Update to Mycelium Offer

### ISSUE THREAD

**Issue by raymogg** [tracer-protocol/proposals#1]
A newly passed proposal (https://snapshot.org/#/tracer.eth/proposal/QmZNz7qweE4S2KE93NtLk2BZ1KY52AgWXrRA2QZedo7Rx5) means the following can now be enacted on chain
- Back payment of approximately U$375,000 (or equivalent), being equivalent to U$75,000 (or equivalent) per month (or part thereof) earned from 10 February 2021 to the day that a Proposal implementing this EOI is executed, pursuant to the Proposal appointing Mycelium, to be paid on the day that a Proposal implementing this EOI is executed;
- A reimbursement of U$96,000 (or equivalent) for the Code 423n4 Audit, as discussed [here](https://discourse.tracer.finance/t/code-423n4-audit-operations/278), to be paid on the day that a Proposal implementing this EOI is executed; and

**Comment by BenjaminPatch** [comment]
Closed because it has been implemented in #2
